version: "3.3"
services:
  upravlyaika_bot:
    build: .
    container_name: upravlyaika_bot
    restart: always
    environment:
      - TZ=Europe/Moscow
    env_file:
      - ./source/.env
    depends_on:
      - upravlyaika_db
    networks:
      - cfu-uprav-bot

  upravlyaika_db:
    image: mysql:8.2.0
    container_name: upravlyaika_db
    restart: always
    ports:
      - 57269:3306
    environment:
      MYSQL_HOST: ${MSQ_HOST}
      MYSQL_DATABASE: ${MSQ_DB}
      MYSQL_USER: ${MSQ_USER}
      MYSQL_PASSWORD: ${MSQ_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MSQ_ROOT_PASSWORD}
      TZ: Europe/Moscow
    networks:
      - cfu-uprav-bot
    depends_on:
      - upravlyaika_cache
    volumes:
      - db_data:/var/lib/mysql

  upravlyaika_cache:
    image: redis:alpine
    container_name: upravlyaika_cache
    restart: always
    ports:
      - 31269:6379
    command: redis-server --requirepass ${RS_PASSWORD}
    networks:
      - cfu-uprav-bot
    volumes:
      - cache:/data

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ~/.databases/uprav_gsheet_my_sql
      o: bind
  cache:
    driver: local
    driver_opts:
      type: none
      device: ~/.databases/uprav_gsheet_redis
      o: bind

networks:
  cfu-uprav-bot:
